"""changed the foreign id column to foreign uuid column name only

Revision ID: 0e8978fc0d8e
Revises: 23277049d2dd
Create Date: 2025-03-06 09:20:08.172571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8978fc0d8e'
down_revision: Union[str, None] = '23277049d2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['uuid'])
    op.add_column('post_categories', sa.Column('post_uuid', sa.UUID(), nullable=False))
    op.add_column('post_categories', sa.Column('category_uuid', sa.UUID(), nullable=True))
    op.add_column('post_categories', sa.Column('sub_category_uuid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'post_categories', ['uuid'])
    op.drop_constraint('post_categories_category_id_fkey', 'post_categories', type_='foreignkey')
    op.drop_constraint('post_categories_sub_category_id_fkey', 'post_categories', type_='foreignkey')
    op.drop_constraint('post_categories_post_id_fkey', 'post_categories', type_='foreignkey')
    op.create_foreign_key(None, 'post_categories', 'categories', ['category_uuid'], ['uuid'])
    op.create_foreign_key(None, 'post_categories', 'sub_categories', ['sub_category_uuid'], ['uuid'])
    op.create_foreign_key(None, 'post_categories', 'posts', ['post_uuid'], ['uuid'])
    op.drop_column('post_categories', 'post_id')
    op.drop_column('post_categories', 'sub_category_id')
    op.drop_column('post_categories', 'category_id')
    op.add_column('sub_categories', sa.Column('category_uuid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'sub_categories', ['uuid'])
    op.drop_constraint('sub_categories_category_id_fkey', 'sub_categories', type_='foreignkey')
    op.create_foreign_key(None, 'sub_categories', 'categories', ['category_uuid'], ['uuid'])
    op.drop_column('sub_categories', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sub_categories', type_='foreignkey')
    op.create_foreign_key('sub_categories_category_id_fkey', 'sub_categories', 'categories', ['category_id'], ['uuid'])
    op.drop_constraint(None, 'sub_categories', type_='unique')
    op.drop_column('sub_categories', 'category_uuid')
    op.add_column('post_categories', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('post_categories', sa.Column('sub_category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('post_categories', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_categories', type_='foreignkey')
    op.drop_constraint(None, 'post_categories', type_='foreignkey')
    op.drop_constraint(None, 'post_categories', type_='foreignkey')
    op.create_foreign_key('post_categories_post_id_fkey', 'post_categories', 'posts', ['post_id'], ['uuid'])
    op.create_foreign_key('post_categories_sub_category_id_fkey', 'post_categories', 'sub_categories', ['sub_category_id'], ['uuid'])
    op.create_foreign_key('post_categories_category_id_fkey', 'post_categories', 'categories', ['category_id'], ['uuid'])
    op.drop_constraint(None, 'post_categories', type_='unique')
    op.drop_column('post_categories', 'sub_category_uuid')
    op.drop_column('post_categories', 'category_uuid')
    op.drop_column('post_categories', 'post_uuid')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
