"""added time_stamp and user_audit

Revision ID: a3821025d736
Revises: dc6408c812ce
Create Date: 2025-03-02 15:04:15.484786

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3821025d736"
down_revision: Union[str, None] = "dc6408c812ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.create_unique_constraint(None, "users", ["uuid"])
    op.create_foreign_key(None, "users", "users", ["updated_by"], ["uuid"])
    op.create_foreign_key(None, "users", "users", ["created_by"], ["uuid"])
    op.create_foreign_key(None, "users", "users", ["deleted_by"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "deleted_by")
    op.drop_column("users", "updated_by")
    op.drop_column("users", "created_by")
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
