"""added the relations and removed the mixins

Revision ID: e4ff916b5379
Revises: 0e8978fc0d8e
Create Date: 2025-03-06 20:24:20.293552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4ff916b5379"
down_revision: Union[str, None] = "0e8978fc0d8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "post_categories_created_by_fkey", "post_categories", type_="foreignkey"
    )
    op.drop_constraint(
        "post_categories_deleted_by_fkey", "post_categories", type_="foreignkey"
    )
    op.drop_constraint(
        "post_categories_updated_by_fkey", "post_categories", type_="foreignkey"
    )
    op.drop_column("post_categories", "updated_by")
    op.drop_column("post_categories", "deleted_by")
    op.drop_column("post_categories", "created_at")
    op.drop_column("post_categories", "deleted_at")
    op.drop_column("post_categories", "created_by")
    op.drop_column("post_categories", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_categories",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "post_categories",
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "post_categories",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "post_categories",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "post_categories",
        sa.Column("deleted_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "post_categories",
        sa.Column("updated_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "post_categories_updated_by_fkey",
        "post_categories",
        "users",
        ["updated_by"],
        ["uuid"],
    )
    op.create_foreign_key(
        "post_categories_deleted_by_fkey",
        "post_categories",
        "users",
        ["deleted_by"],
        ["uuid"],
    )
    op.create_foreign_key(
        "post_categories_created_by_fkey",
        "post_categories",
        "users",
        ["created_by"],
        ["uuid"],
    )
    # ### end Alembic commands ###
